//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyMetadataAttribute("DotNetEfFullPath", "C:\\Users\\wigodbe\\.nuget\\packages\\dotnet-ef/3.0.1/tools/netcoreapp3.0/any/dotnet-e" +
    "f.dll")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestPackageRestorePath", "E:\\code\\aspnet\\aspnetcore\\obj\\template-restore\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestAssemblyApplication[Microsoft.AspNetCore.Components.Authorization, Version=42" +
    ".42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60]", "E:\\code\\aspnet\\aspnetcore\\src\\Components\\Authorization\\src")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestAssemblyApplication[Microsoft.AspNetCore.Components, Version=42.42.42.42, Cul" +
    "ture=neutral, PublicKeyToken=adb9793829ddae60]", "E:\\code\\aspnet\\aspnetcore\\src\\Components\\Components\\src")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestAssemblyApplication[Microsoft.AspNetCore.Components.Forms, Version=42.42.42.4" +
    "2, Culture=neutral, PublicKeyToken=adb9793829ddae60]", "E:\\code\\aspnet\\aspnetcore\\src\\Components\\Forms\\src")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestAssemblyApplication[Microsoft.AspNetCore.Components.Server, Version=42.42.42." +
    "42, Culture=neutral, PublicKeyToken=adb9793829ddae60]", "E:\\code\\aspnet\\aspnetcore\\src\\Components\\Server\\src")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestAssemblyApplication[Microsoft.AspNetCore.Components.Web, Version=42.42.42.42," +
    " Culture=neutral, PublicKeyToken=adb9793829ddae60]", "E:\\code\\aspnet\\aspnetcore\\src\\Components\\Web\\src")]
[assembly: System.Reflection.AssemblyMetadataAttribute("Microsoft.AspNetCore.Testing.Selenium.Supported", "true")]
[assembly: System.Reflection.AssemblyMetadataAttribute("Microsoft.AspNetCore.Testing.Selenium.ProcessTracking", "E:\\code\\aspnet\\aspnetcore\\artifacts\\tmp\\selenium\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("ArtifactsShippingPackagesDir", "E:\\code\\aspnet\\aspnetcore\\artifacts\\packages\\Debug\\Shipping\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("ArtifactsNonShippingPackagesDir", "E:\\code\\aspnet\\aspnetcore\\artifacts\\packages\\Debug\\NonShipping\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestTemplateCreationFolder", "E:\\code\\aspnet\\aspnetcore\\src\\ProjectTemplates\\test\\bin\\Debug\\netcoreapp3.0\\TestT" +
    "emplates\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("CustomTemplateHivePath", "E:\\code\\aspnet\\aspnetcore\\src\\ProjectTemplates\\test\\bin\\Debug\\netcoreapp3.0\\TestT" +
    "emplates\\\\Hives\\abbf5f6a-e71b-4805-b801-4ffde255a5f1\\.templateengine")]
[assembly: Xunit.TestFramework("Microsoft.Extensions.Logging.Testing.LoggedTestFramework", "Microsoft.Extensions.Logging.Testing")]
[assembly: Microsoft.Extensions.Logging.Testing.TestFrameworkFileLoggerAttribute("netcoreapp3.0", "E:\\code\\aspnet\\aspnetcore\\artifacts\\log\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("CommitHash", "f59a0910a33a312b863d07b65378e83ae3c47239")]
[assembly: System.Reflection.AssemblyMetadataAttribute("SourceCommitUrl", "https://github.com/aspnet/AspNetCore/tree/f59a0910a33a312b863d07b65378e83ae3c4723" +
    "9")]
[assembly: System.Reflection.AssemblyMetadataAttribute("Serviceable", "True")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© Microsoft Corporation. All rights reserved.")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("\r\n\r\nTo install the templates in this package, run \'dotnet new --install ProjectTe" +
    "mplates.Tests::3.0.1-dev\'.\r\n    ")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("42.42.42.42424")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.0.1-dev")]
[assembly: System.Reflection.AssemblyProductAttribute("Microsoft ASP.NET Core")]
[assembly: System.Reflection.AssemblyTitleAttribute("ProjectTemplates.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("42.42.42.42")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")]

// Generated by the MSBuild WriteCodeFragment class.

