//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyMetadataAttribute("Microsoft.AspNetCore.E2ETesting.CI", "False")]
[assembly: System.Reflection.AssemblyMetadataAttribute("Microsoft.AspNetCore.E2ETesting.ScreenshotsPath", "E:\\code\\aspnet\\aspnetcore\\artifacts\\TestResults\\Debug\\ProjectTemplates.Tests\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("DotNetEfFullPath", "C:\\Users\\wigodbe\\.nuget\\packages\\dotnet-ef/5.0.0-alpha1.19517.14/tools/netcoreapp" +
    "5.0/any/dotnet-ef.dll")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestPackageRestorePath", "E:\\code\\aspnet\\aspnetcore\\obj\\template-restore\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("Microsoft.AspNetCore.Testing.Selenium.Supported", "true")]
[assembly: System.Reflection.AssemblyMetadataAttribute("Microsoft.AspNetCore.Testing.Selenium.ProcessTracking", "E:\\code\\aspnet\\aspnetcore\\artifacts\\tmp\\selenium\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("ArtifactsShippingPackagesDir", "E:\\code\\aspnet\\aspnetcore\\artifacts\\packages\\Debug\\Shipping\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("ArtifactsLogDir", "E:\\code\\aspnet\\aspnetcore\\artifacts\\log\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("ArtifactsNonShippingPackagesDir", "E:\\code\\aspnet\\aspnetcore\\artifacts\\packages\\Debug\\NonShipping\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("TestTemplateCreationFolder", "E:\\code\\aspnet\\aspnetcore\\src\\ProjectTemplates\\test\\bin\\Debug\\netcoreapp5.0\\TestT" +
    "emplates\\")]
[assembly: System.Reflection.AssemblyMetadataAttribute("CustomTemplateHivePath", "E:\\code\\aspnet\\aspnetcore\\src\\ProjectTemplates\\test\\bin\\Debug\\netcoreapp5.0\\TestT" +
    "emplates\\\\Hives\\0fbc17f6-fcb5-4d16-966b-541be981c7a8\\.templateengine")]
[assembly: System.Reflection.AssemblyMetadataAttribute("CommitHash", "a4d9faefe2ed6fbebd500413032336607ec92778")]
[assembly: System.Reflection.AssemblyMetadataAttribute("SourceCommitUrl", "https://github.com/aspnet/AspNetCore/tree/a4d9faefe2ed6fbebd500413032336607ec9277" +
    "8")]
[assembly: System.Reflection.AssemblyMetadataAttribute("Serviceable", "True")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© Microsoft Corporation. All rights reserved.")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("\r\n\r\nTo install the templates in this package, run \'dotnet new --install ProjectTe" +
    "mplates.Tests::5.0.0-dev\'.\r\n    ")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("42.42.42.42424")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("5.0.0-dev")]
[assembly: System.Reflection.AssemblyProductAttribute("Microsoft ASP.NET Core")]
[assembly: System.Reflection.AssemblyTitleAttribute("ProjectTemplates.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("42.42.42.42")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")]

// Generated by the MSBuild WriteCodeFragment class.

